### ISSUE TITLE
graphviz link is "forbidden"

### ISSUE THREAD

**Issue by vitiral** [NixOS/nix-pills#50]
The link given in [section 12.3](https://nixos.org/nixos/nix-pills/inputs-design-pattern.html#idm140737316015392) results in "forbidden" for me:
```
$ wget http://pkgs.fedoraproject.org/repo/pkgs/graphviz/graphviz-2.38.0.tar.gz/5b6a829b2ac94efcd5fa3c223ed6d3ae/graphviz-2.38.0.tar.gz                                                                          
--2018-02-25 13:15:08--  http://pkgs.fedoraproject.org/repo/pkgs/graphviz/graphviz-2.38.0.tar.gz/5b6a829b2ac94efcd5fa3c223ed6d3ae/graphviz-2.38.0.tar.gz                                                          
Resolving pkgs.fedoraproject.org (pkgs.fedoraproject.org)... 209.132.181.4                                                                                                                                        
Connecting to pkgs.fedoraproject.org (pkgs.fedoraproject.org)|209.132.181.4|:80... connected.                                                                                                                     
HTTP request sent, awaiting response... 403 Forbidden                                                                                                                                                             
2018-02-25 13:15:08 ERROR 403: Forbidden.
```

**Comment by vitiral** [comment]
You can download the latest stable release from: https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz

Not sure how to download a specific release

**Comment by vitiral** [comment]
that version fails using the current guide (but with my fix in #43) with the following errors:

```
malloc.c: At top level:   
malloc.c:331:15: error: return type is an incomplete type
 struct mstats mstats(void)                                                                                           
               ^~~~~~      
malloc.c:331:15: warning: no previous prototype for 'mstats' [-Wmissing-prototypes]
malloc.c: In function 'mstats':                                   
malloc.c:334:19: error: storage size of 'ms' isn't known 
     struct mstats ms;     
                   ^~         
...

builder for ‘/nix/store/zpbqkv4cx8s6jhfsb4blxap6zzdxw068-graphviz.drv’ failed with exit code 2
error: build of ‘/nix/store/zpbqkv4cx8s6jhfsb4blxap6zzdxw068-graphviz.drv’ failed
```

I'm not a C developer, so not sure how to proceed there.

**Comment by takeda** [comment]
I got the same version from: https://src.fedoraproject.org/repo/pkgs/graphviz/graphviz-2.38.0.tar.gz/5b6a829b2ac94efcd5fa3c223ed6d3ae/graphviz-2.38.0.tar.gz

Anyway, I'm getting this when compiling graphviz on OS X:

```
compile.c:629:5: note: variable 'v' is declared here
    Extype_t v;
    ^
1 warning generated.
  CC       gvpr.lo
  CC       gprstate.lo
  CC       parse.lo
  CC       queue.lo
  CCLD     libgvpr.la
ld: warning: directory not found for option '-L/nix/store/q793wrzzwpxv5s4whqqb01kwlkicpvhi-graphviz/lib'
Undefined symbols for architecture x86_64:
  "_qfrexp", referenced from:
      __sfdlen in libexpr_C.a(sfdlen.o)
      __sfputd in libexpr_C.a(sfputd.o)
  "_qldexp", referenced from:
      __sfdlen in libexpr_C.a(sfdlen.o)
      _sfgetd in libexpr_C.a(sfgetd.o)
      __sfputd in libexpr_C.a(sfputd.o)
ld: symbol(s) not found for architecture x86_64
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Makefile:656: libgvpr.la] Error 1
make[3]: Leaving directory '/private/tmp/nix-build-graphviz.drv-0/graphviz-2.38.0/lib/gvpr'
make[2]: *** [Makefile:536: all-recursive] Error 1
make[2]: Leaving directory '/private/tmp/nix-build-graphviz.drv-0/graphviz-2.38.0/lib'
make[1]: *** [Makefile:774: all-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-graphviz.drv-0/graphviz-2.38.0'
make: *** [Makefile:583: all] Error 2
builder for '/nix/store/s18n9adlvybw8d8g01aslfxiy54av33v-graphviz.drv' failed with exit code 2
error: build of '/nix/store/s18n9adlvybw8d8g01aslfxiy54av33v-graphviz.drv' failed
```

I already fixed the issue with gcc/clang (use stdenv.cc) and binutils (use binutils.bintools) mentioned in other issues and sadly on nearly every step I'm running into issues, and using this tutorial as a nix newb makes it harder to move on.

Perhaps using C in the tutorial is not the best idea since looks like nix on OS X uses a different compiler than Linux.
